In [3]:
# Please do not change this cell because some hidden tests might depend on it.
import os

# Otter grader does not handle ! commands well, so we define and use our
# own function to execute shell commands.
def shell(commands, warn=True):
    """Executes the string `commands` as a sequence of shell commands.
     
       Prints the result to stdout and returns the exit status. 
       Provides a printed warning on non-zero exit status unless `warn` 
       flag is unset.
    """
    file = os.popen(commands)
    print (file.read().rstrip('\n'))
    exit_status = file.close()
    if warn and exit_status != None:
        print(f"Completed with errors. Exit status: {exit_status}\n")
    return exit_status

shell("""
ls requirements.txt >/dev/null 2>&1
if [ ! $? = 0 ]; then
 rm -rf .tmp
 git clone https://github.com/cs187-2021/lab1-1.git .tmp
 mv .tmp/tests ./
 mv .tmp/requirements.txt ./
 rm -rf .tmp
fi
pip install -q -r requirements.txt
""")

In [4]:
# Initialize Otter
import otter
grader = otter.Notebook()

# CS187
## Lab 1-1 – Types, tokens, and representing text

In [5]:
import math
import re
import sys

import torch
import torchtext.legacy as tt

Where we're headed: Nearest neighbor text classification works by classifying a novel text with the same class as that of the training text that is closest according to some distance metric. These metrics are calculated based on representations of the texts. In this lab, we'll introduce some different representations and you'll use nearest neighbor classification to predict the speaker of sentences selected from a children's book.
    
The objectives of this lab are to:

* Clarify terminology around words and texts,
* Manipulate different representations of words and texts,
* Apply these representations to calculate text similarity, and
* Classify documents by a simple nearest neighbor model.
   
In this and later labs, we will have you carry out several exercises in notebook cells. The cells you are to do are marked '`#TODO`'. They will typically have a `...` where your code or answer should go. Where specified, you needn't write code to calculate the answer, but instead, simply work out the answer yourself and enter it.

New bits of Python used for the first time in the _solution set_ for this lab, and which you may therefore find useful:

* `math.acos`
* `math.pi`
* `re.match`
* `set`
* `sorted`
* `str.join`
* `str.lower`
* `torch.dot`
* `torch.linalg.norm`
* `torch.maximum`
* `torch.minimum`
* `torch.stack`
* `torch.sum`
* `torch.Tensor.type`
* `torch.where`
* `torch.zeros`
* `torch.zeros_like`
* `torchtext.data.get_tokenizer`

# Counting words

<img src="https://github.com/nlp-course/data/blob/master/Seuss/seuss%20-%201966%20-%20green%20eggs%20and%20ham.gif?raw=true" width=150 align=right />

Here are five sentences from Dr. Seuss's [_Green Eggs and Ham_](https://en.wikipedia.org/wiki/Green_Eggs_and_Ham):

    Would you like them here or there?
    I would not like them here or there.
    I would not like them anywhere.
    I do not like green eggs and ham.
    I do not like them, Sam-I-am.

We'll make this text available in the variable `text`.

In [6]:
text = """
    Would you like them here or there?
    I would not like them here or there.
    I would not like them anywhere.
    I do not like green eggs and ham.
    I do not like them, Sam-I-am.
    """

A Python string like this is, of course, a sequence of characters. But we think of this text as a sequence of sentences each composed of a sequence of words. How many words are there in this text? That is a fraught question, for several reasons, including

* The type-token distinction
* Tokenization issues
* Normalization

## Types versus tokens

In determining the number of words in `text`, are we talking about word _types_ or word _tokens_. (For instance, there are five _tokens_ of the word _type_ 'like'.)

How many word tokens are there in total in this text? (Just count them manually.) Assign the number to the variable `token_count` in the next cell.
<!--
BEGIN QUESTION
name: token_count
-->

In [7]:
#TODO - define `token_count` to be the number of tokens in `text`
token_count = 35

In [8]:
grader.check("token_count")

All tests passed!

How many word types are there? (Again, you can just count manually.)
<!--
BEGIN QUESTION
name: type_count
-->

In [9]:
#TODO - define `type_count` to be the number of types in `text`
type_count = 16

In [10]:
grader.check("type_count")

All tests passed!

<!-- BEGIN QUESTION -->

The set of types of a language is referred to as its _vocabulary_. Are there more types or tokens as you calculated above? Could it be otherwise?
<!--
BEGIN QUESTION
name: type_vs_token_count
manual: true
-->

There are more types than tokens. It couldn't be otherwise, the maximum number of types is the number of tokens if every word in the corpus was distinct. Otherwise, the number of types would always be less than the number of tokens. 

<!-- END QUESTION -->



## Tokenization 

Did you count 'there?' as one token or two? This raises the issue of _tokenization_ of text, how to decide where the token boundaries occur. For instance, here's a simple way to split a string – to _tokenize_ it – in Python by splitting at whitespace.

In [11]:
def whitespace_tokenize(str):
    return str.split()

Try it out on the `text` defined above.
<!--
BEGIN QUESTION
name: tokens_whitespace
-->

In [12]:
#TODO - define `tokens` to be the tokens as defined by the `whitespace_tokenize` function
tokens = whitespace_tokenize(text)

In [13]:
grader.check("tokens_whitespace")

All tests passed!

Using this tokenization method, count the number of tokens in the text, this time using Python to do the work.
<!--
BEGIN QUESTION
name: token_count_whitespace
-->

In [14]:
#TODO - place your token count here
token_count_2 = len(tokens)

In [15]:
grader.check("token_count_whitespace")

All tests passed!

Arguably, we _should_ split off punctuation as separate tokens, but even there, some care must be taken. We don't want to split 'don't' into three tokens or 'Sam-I-Am' into five. (There's a good argument to be made however that the string 'don't' should be construed as two tokens, namely, 'do' and 'n't', but that's beyond the scope of today's discussion.)

Here, we provide an alternative tokenizer that splits tokens at whitespace and splits off punctuation at the beginning and end of non-whitespace regions as separate tokens as well. It makes use of [the Python `re` module](https://docs.python.org/3/library/re.html) for regular expressions to specify the splitting process. Look over the code and make sure you understand what's going on. You might find [this online tool](https://regexr.com/) useful.

In [16]:
def punc_tokenize(str):
    return [tok for tok in re.split('(\W*?)\s+', str) if tok != '']

Now how many tokens are there in the text if tokenized in this way?
<!--
BEGIN QUESTION
name: token_count_punc
-->

In [17]:
#TODO
token_count_3 = len(punc_tokenize(text))
print(punc_tokenize(text))

['Would', 'you', 'like', 'them', 'here', 'or', 'there', '?', 'I', 'would', 'not', 'like', 'them', 'here', 'or', 'there', '.', 'I', 'would', 'not', 'like', 'them', 'anywhere', '.', 'I', 'do', 'not', 'like', 'green', 'eggs', 'and', 'ham', '.', 'I', 'do', 'not', 'like', 'them', ',', 'Sam-I-am', '.']


In [18]:
grader.check("token_count_punc")

All tests passed!

## Normalization

This tokenization method counts 'Would' and 'would' (capitalized and uncapitalized) as separate types. Is that a good idea? This raises the issue of text _normalization_.

Define a function `normalize_token` that normalizes tokens by making them lowercase if at most the first character is uppercase. (Hints [here](https://docs.python.org/3/library/stdtypes.html#str.lower) and [here](https://docs.python.org/3/library/re.html#re.match). These are also listed in the hint cell at the top of the lab, so we'll mostly stop providing these hints from here on.)
<!--
BEGIN QUESTION
name: normalize_token
-->

In [19]:
#TODO - implement normalize_token, which returns the normalized word for a single word `str`
def normalize_token(str):
    upperCount = 0
    for char in str:
        if(char.isupper()):
            upperCount += 1
    if(str[0].isupper() and upperCount <= 1):
        return str.lower()
    else:
        return str

In [20]:
grader.check("normalize_token")

All tests passed!

Now define `norm_tokens_punc` to be the sequence of normalized tokens as tokenized by `punc_tokenize`
<!--
BEGIN QUESTION
name: norm_tokens_punc
-->

In [21]:
#TODO
norm_tokens_punc = [normalize_token(tok) for tok in punc_tokenize(text)]
print(norm_tokens_punc)

['would', 'you', 'like', 'them', 'here', 'or', 'there', '?', 'i', 'would', 'not', 'like', 'them', 'here', 'or', 'there', '.', 'i', 'would', 'not', 'like', 'them', 'anywhere', '.', 'i', 'do', 'not', 'like', 'green', 'eggs', 'and', 'ham', '.', 'i', 'do', 'not', 'like', 'them', ',', 'Sam-I-am', '.']


In [22]:
grader.check("norm_tokens_punc")

All tests passed!

How many types are there when tokenized and normalized in this way?
<!--
BEGIN QUESTION
name: type_count_norm_punc
-->

In [23]:
#TODO
type_count_norm_punc = len(set(norm_tokens_punc))
print(set(norm_tokens_punc))

{'them', 'not', 'do', 'would', 'there', 'like', 'green', 'anywhere', 'here', 'i', ',', '?', 'you', '.', 'ham', 'and', 'Sam-I-am', 'or', 'eggs'}


In [24]:
grader.check("type_count_norm_punc")

All tests passed!

## Using prebuilt tokenizers

Tokenization and normalization are so commonly needed that many packages provide pre-built tokenizers of various sorts. We'll use one from `torchtext`, a package that we'll make a fair amount of use of in the course. It's already been imported above under the name `tt`.

Define two tokenizers, versions of `whitespace_tokenize` and a normalized version of `punc_tokenize` above, using [the `tt.data.get_tokenizer` function](https://pytorch.org/text/stable/data_utils.html#get-tokenizer). (Use respectively the `None` and `"basic_english"` tokenizers that they provide.)
<!--
BEGIN QUESTION
name: tt_whitespace_tokenize_and_tt_normpunc_tokenize
-->

In [25]:
#TODO
def tt_whitespace_tokenize(str):
    tokenizer = tt.data.get_tokenizer(None)
    tokens = tokenizer(str)
    return tokens
    
def tt_normpunc_tokenize(str):
    tokenizer = tt.data.get_tokenizer("basic_english")
    tokens = tokenizer(str)
    return tokens

In [26]:
grader.check("tt_whitespace_tokenize_and_tt_normpunc_tokenize")

All tests passed!

Now we should be able to print out the last few tokens of the sample text, tokenized using these functions.

In [27]:
print(tt_whitespace_tokenize(text)[-10:])
print(tt_normpunc_tokenize(text)[-10:])

['green', 'eggs', 'and', 'ham.', 'I', 'do', 'not', 'like', 'them,', 'Sam-I-am.']
['ham', '.', 'i', 'do', 'not', 'like', 'them', ',', 'sam-i-am', '.']


> _Meta-comment:_ Because it's important that you get practice both with implementing the ideas in the course from first principles and also with using prebuilt software that provides similar functionality, we'll often have you engage in this seemingly redundant process of first implementing a small example and then applying a prebuilt method to do much the same thing. The effort may be duplicative, but it is not wasted.

# Representing words

In this section, we'll explore some simple representations for tokens, as a step on the way to representing texts – sentences or documents:

## String encoding
We've already seen string encoding above, representing a token of a word type by a string specific to that type: a token 'green' represented by an instance of the Python string `'green'`, for instance, or 'Sam-I-am' represented by `'Sam-I-am'`. So let's move on.

## 1-hot encoding
Given a vocabulary for a language, we can associate each type with an integer, say by its index in a vector. We've already imported the `torch` module; we'll use `torch` tensors for the index vector. For the Seuss text, we can use this list to represent the ordered vocabulary:

In [28]:
vocabulary = sorted(set(norm_tokens_punc))
vocabulary

[',',
 '.',
 '?',
 'Sam-I-am',
 'and',
 'anywhere',
 'do',
 'eggs',
 'green',
 'ham',
 'here',
 'i',
 'like',
 'not',
 'or',
 'them',
 'there',
 'would',
 'you']

### A digression on `torch` tensors

Recall that `torch` tensors allow for vectorized computations: many operations on them work [componentwise](https://en.wikipedia.org/wiki/Pointwise#Componentwise_operations), that is, separately for each component of the tensor, rather than on the tensor all at once. Compare the following two operations, first on lists, then on `torch` tensors.

In [29]:
[1, 2] == 1

False

In [30]:
torch.tensor([1, 2]) == 1

tensor([ True, False])

This behavior of tensors is quite powerful, allowing for simply specifying complex operations and for efficient, even parallelizable, computation of them. You'll want ot take advantage of these characteristics of tensors where possible, here and in future assignments.

But back to the 1-hot representation.

In the _1-hot representation_ of words, a token is then represented by a bit vector (again given as a `torch` tensor), with a 1 at the index of the token's type. (For consistency with some later `torch` functions, we'll take the elements to be floats rather than ints. The `.type` method is useful for converting the type, and it even conveniently broadcasts over the tensors.) For instance, the 1-hot representation of the comma token ',' would be

In [31]:
torch.tensor([1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]).type(torch.float32)

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])

Conversion back and forth between these various representations is useful. Define functions `str_to_onehot` and `onehot_to_str` that convert between the string and one-hot representations using a vocabulary array to define the  conversion. 

Ideally, in your implementation, you'll want to take advantage of the componentwise nature of many tensor operations discussed above.

In [32]:
#TODO
def str_to_onehot(wordtype, vocab):
    """Returns the 1-hot representation of `wordtype` with vocabulary 
    `vocab`.
    The returned value should be a torch.tensor with data type float.
    """
    arr = [0 for word in vocab]
    for i in range(len(vocab)):
        if(vocab[i] == wordtype):
            arr[i] = 1
    return torch.tensor(arr).type(torch.float32)
    

def onehot_to_str(onehot, vocab):
    """Returns the string representation of `onehot`, a one-hot 
    representation of a word type, with vocabulary `vocab`.
    """
    numMapping = onehot.tolist()
    return vocab[numMapping.index(1.)]
    

Now use `str_to_onehot` to define the variable `anywhere_1hot` to be the 1-hot representation for a token of the type 'anywhere'. 
<!--
BEGIN QUESTION
name: anywhere_1hot
-->

In [33]:
#TODO
anywhere_1hot = str_to_onehot('anywhere', vocabulary)

In [34]:
grader.check("anywhere_1hot")

All tests passed!

You can verify that the conversion worked correctly by inverting it using `onehot_to_str`, which we've done in the following unit test.
<!--
BEGIN QUESTION
name: anywhere_1hot_reverse
-->

In [35]:
grader.check("anywhere_1hot_reverse")

All tests passed!

# Representing texts

## The set-of-words representation

We can represent a whole text (a sequence of words) by manipulating the vector representations of the words within the text. For instance, we can take the componentwise maximum of the vectors. We refer to this as the _set-of-words_ representation.

Here we've defined a function `set_of_words` that returns the set of words representation for a token sequence.

In [36]:
def set_of_words(tokens, vocabulary):
    """Returns the set-of-words representation as a tensor of floats for the 
    sequence of `tokens` using the `vocabulary` to specify the conversion.
    """
    onehots = torch.stack([str_to_onehot(token, vocabulary) for token in tokens])
    #print(onehots)
    return torch.amax(onehots, 0).type(torch.float32)

This representation for a text is a vector that has a `1` for each word type that occurs in the text. The vector represents the [characteristic function](https://en.wikipedia.org/wiki/Characteristic_function) for the subset of vocabulary words that appear in the text; hence the term 'set of words'.


What is the set-of-words representation for the example text 'I would not, would not, here or there.'?
<!--
BEGIN QUESTION
name: example_sow
-->

In [37]:
#TODO - define the variable to be the set of words representation for the example text
# 'I would not, would not, here or there.'
# Use `tt_normpunc_tokenize` tokenizer
text = 'I would not, would not, here or there.'
tokens = tt_normpunc_tokenize(text)
#print(tokens)
example_sow = set_of_words(tokens, vocabulary)
#print(example_sow)

In [38]:
grader.check("example_sow")

All tests passed!

## The bag of words representation

If instead, we take the componentwise _addition_ of the vectors instead of the maximum, the text representation provides the _frequency_ of each word type in the text. We refer to this representation as the _[bag](https://en.wikipedia.org/wiki/Multiset) of words_ representation. 

Define a function `bag_of_words`, analogous to `set_of_words` above, that returns the bag-of-words representation for a token sequence.

In [39]:
#TODO
def bag_of_words(tokens, vocabulary):
    bag = 0
    for token in tokens:
        bag += str_to_onehot(token, vocabulary)
    return bag
    
     

What is the bag of words representation for the example text 'I would not, would not, here or there.'?
<!--
BEGIN QUESTION
name: example_bow
-->

In [40]:
#TODO - define the variable to be the bag of words representation for the example text
# 'I would not, would not, here or there.'
# Use the `tt_normpunc_tokenize` tokenizer
text = 'I would not, would not, here or there.'
tokens = tt_normpunc_tokenize(text)
example_bow = bag_of_words(tokens, vocabulary)
print(example_bow)

tensor([2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 2., 1., 0., 1., 2.,
        0.])


In [41]:
grader.check("example_bow")

All tests passed!

# Document similarity metrics

Consider the following text classification problem: Each sentence in _Green Eggs and Ham_ is spoken by one of two characters, Sam-I-Am and Guy-Am-I. We want to be able to classify new sentences as (most likely) being uttered by one of the two.

A simple method for text classification is the _nearest neighbor_ method. We select the class for the new sentence that is the same as the class of the "nearest" (most similar) sentence for which we already know the class. (You'll experiment much more with this text classification method in the next lab.)

To perform nearest neighbor classification, we need a method for measuring the (metaphorical) distance between two texts based on their representations. We'll explore a few methods here:

* Hamming distance
* Jaccard distance
* Euclidean distance
* cosine distance

You'll implement code for all of these distance metrics. Try to implement the functions using `torch` tensor functions only, without explicit iteration over the elements in the vector.

We'll take a look at the distances among the following sentences:

1. Would you like them here or there?
2. I would not like them here or there.
3. Do you like green eggs and ham?
4. I do not like them Sam-I-Am.

We'll start with the set of words representations of these sentences:

In [42]:
examples = """Would you like them here or there?
              I would not like them here or there.
              Do you like green eggs and ham?
              I do not like them Sam-I-Am.""" \
           .split("\n")
sows = [set_of_words(tt_normpunc_tokenize(sentence), vocabulary) 
            for sentence in examples]

In [43]:
sows

[tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
         1.]),
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
         0.]),
 tensor([0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
         1.]),
 tensor([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
         0.])]

## Hamming distance

The Hamming distance between two vectors is the number of positions at which they differ. Define a function `hamming_distance` that computes the Hamming distance between two vectors.
<!--
BEGIN QUESTION
name: hamming_distance
-->

In [44]:
#TODO - implement hamming_distance. The returned value should be an integer.
def hamming_distance(v1, v2):
    hd = sum(abs(v1-v2))
    return hd

In [45]:
grader.check("hamming_distance")

All tests passed!

Now we can generate the Hamming distances among all of the sample sentences in a little table. Do the values make sense?

In [46]:
for i in range(4):
    for j in range(4):
        print(f"{hamming_distance(sows[i], sows[j]):4} ", end='')
    print()

 0.0  5.0 10.0 10.0 
 5.0  0.0 15.0  5.0 
10.0 15.0  0.0 10.0 
10.0  5.0 10.0  0.0 


## Jaccard distance

The Jaccard distance between two sets (and remember that these bit strings basically represent sets) is one minus the number of elements in their intersection divided by the number of elements in their union.

$$ D_{jaccard}(v_1, v_2) = 1 - \frac{| v_1 \cap v_2 |}{| v_1 \cup v_2 |} $$

Define a function `jaccard_distance` to compute the Jaccard distance between two set-of-words representations.
<!--
BEGIN QUESTION
name: jaccard_distance
-->

In [71]:
#TODO
def jaccard_distance(v1, v2):
    union = sum(torch.logical_or(v1,v2))
    intersection = sum(torch.logical_and(v1,v2))
        
        
    return torch.tensor(1) - (intersection/union)

In [72]:
grader.check("jaccard_distance")

All tests passed!

Again, here's a table of the Jaccard distances among the sample sentences.

In [73]:
for i in range(4):
    for j in range(4):
        print(f"{jaccard_distance(sows[i], sows[j]):5.3f} ", end='')
    print()

0.000 0.455 0.769 0.833 
0.455 0.000 0.938 0.500 
0.769 0.938 0.000 0.833 
0.833 0.500 0.833 0.000 


## Euclidean distance

The Euclidean distance between two vectors is the norm of the vector between them, that is,

$$ D_{euclidean}(\mathbf{x}, \mathbf{y}) = |\mathbf{x} - \mathbf{y}| $$

where $|\mathbf{z}|$, the norm of a vector $\mathbf{z}$, is calculated as

$$ |\mathbf{z}| = \sqrt{\sum_{i=1}^N \mathbf{z}_i^2} $$

Fortunately, `torch` provides the function [`torch.linalg.norm`](https://pytorch.org/docs/stable/generated/torch.linalg.norm.html#torch.linalg.norm) to compute the norm, and the vector between two vectors can be computed by componentwise subtraction.

Define a function `euclidean_distance` to compute the Euclidean distance between two vectors.
<!--
BEGIN QUESTION
name: euclidean_distance
-->

In [74]:
#TODO
def euclidean_distance(v1, v2):
    return (torch.linalg.norm(v1-v2))

In [75]:
grader.check("euclidean_distance")

All tests passed!

Again, here's a table of the Euclidean distances among the sample sentences.

In [76]:
for i in range(4):
    for j in range(4):
        print(f"{euclidean_distance(sows[i], sows[j]):5.3f} ", end='')
    print()

0.000 2.236 3.162 3.162 
2.236 0.000 3.873 2.236 
3.162 3.873 0.000 3.162 
3.162 2.236 3.162 0.000 


In [53]:
def safe_acos(x):
    """Returns the arc cosine of `x`. Unlike `math.acos`, it 
       does not raise an exception for values of `x` out of range, 
       but rather clips `x` at -1..1, thereby avoiding math domain
       errors in the case of numerical errors."""
    return math.acos(math.copysign(min(1.0, abs(x)), x))

In [54]:
#TODO
def cosine_distance(v1, v2):
    """Returns the cosine distance between two vectors"""
    cosNum = torch.dot(v1,v2)
    cosDenom = torch.linalg.norm(v1) * torch.linalg.norm(v2)
    num = safe_acos(cosNum/cosDenom)
    
    return num/math.pi

In [55]:
grader.check("cosine_distance")

All tests passed!

In [56]:
for i in range(4):
    for j in range(4):
        print(f"{cosine_distance(sows[i], sows[j]):5.3f} ", end='')
    print()

0.000 0.250 0.378 0.407 
0.250 0.000 0.462 0.262 
0.378 0.462 0.000 0.407 
0.407 0.262 0.407 0.000 


In the next lab, you'll use some of these distance metrics to automatically classify text using nearest neighbor classification.

<!-- BEGIN QUESTION -->

# Lab debrief – for consensus submission only

**Question:** We're interested in any thoughts your group has about this lab so that we can improve this lab for later years, and to inform later labs for this year. Please list any issues that arose or comments you have to improve the lab. Useful things to comment on include the following: 

* Was the lab too long or too short?
* Were the readings appropriate for the lab? 
* Was it clear (at least after you completed the lab) what the points of the exercises were? 
* Are there additions or changes you think would make the lab better?

<!--
BEGIN QUESTION
name: open_response_debrief
manual: true
-->

I think the lab was pretty long. There were a lot of parts to it and a lot to understand. I don't think the tests were good because I wasn't really able to check anything by way of the tests. They were checking very general things and not specific answers, which made it very difficult to understand whether I was working on the project correctly

<!-- END QUESTION -->



# Submission Instructions

This lab should be submitted to Gradescope at <http://go.cs187.info/lab1-1-submit>, which will be made available some time before the due date.

Make sure that you have passed all public tests by running `grader.check_all()` below before submitting. Note that there are hidden tests on Gradescope, the results of which will be revealed after the submission deadline.

# End of lab 1-1

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [66]:
grader.check_all()

anywhere_1hot:

    All tests passed!
    

anywhere_1hot_reverse:

    All tests passed!
    

cosine_distance:

    All tests passed!
    

euclidean_distance:

    All tests passed!
    

example_bow:

    All tests passed!
    

example_sow:

    All tests passed!
    

hamming_distance:

    All tests passed!
    

jaccard_distance:

    All tests passed!
    

norm_tokens_punc:

    All tests passed!
    

normalize_token:

    All tests passed!
    

token_count:

    All tests passed!
    

token_count_punc:

    All tests passed!
    

token_count_whitespace:

    All tests passed!
    

tokens_whitespace:

    All tests passed!
    

tt_whitespace_tokenize_and_tt_normpunc_tokenize:

    All tests passed!
    

type_count:

    All tests passed!
    

type_count_norm_punc:

    All tests passed!